"""
database.py – SQLAlchemy models and database initialization for LearnFlow AI.
This file defines all database tables and seeds demo data for Arthi.
"""

from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime, date, timedelta
import json
import random

db = SQLAlchemy()


# ─────────────────────────────────────────────
# Model Definitions
# ─────────────────────────────────────────────

class User(UserMixin, db.Model):
    """Stores student account and gamification data."""
    __tablename__ = 'users'

    id            = db.Column(db.Integer, primary_key=True)
    name          = db.Column(db.String(100), nullable=False)
    email         = db.Column(db.String(150), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    xp            = db.Column(db.Integer, default=0)
    streak        = db.Column(db.Integer, default=0)
    badges        = db.Column(db.Text, default='[]')   # JSON list
    subject       = db.Column(db.String(100), default='Machine Learning')
    created_at    = db.Column(db.DateTime, default=datetime.utcnow)
    last_login    = db.Column(db.DateTime)

    # Relationships
    activities      = db.relationship('LearningActivity', backref='user', lazy=True, cascade='all, delete-orphan')
    quiz_results    = db.relationship('QuizResult',       backref='user', lazy=True, cascade='all, delete-orphan')
    recommendations = db.relationship('Recommendation',   backref='user', lazy=True, cascade='all, delete-orphan')
    checkins        = db.relationship('DailyCheckin',     backref='user', lazy=True, cascade='all, delete-orphan')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_badges(self):
        try:
            return json.loads(self.badges)
        except Exception:
            return []

    def add_badge(self, badge_name):
        """Add a badge if not already earned. Returns True if newly earned."""
        current = self.get_badges()
        if badge_name not in current:
            current.append(badge_name)
            self.badges = json.dumps(current)
            return True
        return False

    def add_xp(self, amount):
        """Add XP points to the student."""
        self.xp = (self.xp or 0) + amount


class LearningActivity(db.Model):
    """Daily learning activity log."""
    __tablename__ = 'learning_activity'

    id              = db.Column(db.Integer, primary_key=True)
    user_id         = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    date            = db.Column(db.Date,    default=date.today)
    study_hours     = db.Column(db.Float,   default=0.0)
    quiz_score      = db.Column(db.Float,   default=0.0)
    response_time   = db.Column(db.Float,   default=45.0)  # seconds per question
    engagement_level= db.Column(db.Integer, default=3)     # 1–5
    topics_studied  = db.Column(db.String(300), default='')
    created_at      = db.Column(db.DateTime, default=datetime.utcnow)


class QuizResult(db.Model):
    """Stores quiz attempts and results."""
    __tablename__ = 'quiz_results'

    id            = db.Column(db.Integer, primary_key=True)
    user_id       = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    topic         = db.Column(db.String(100), nullable=False)
    score         = db.Column(db.Float, nullable=False)   # 0–100
    difficulty    = db.Column(db.String(20), default='easy')
    num_questions = db.Column(db.Integer, default=5)
    correct       = db.Column(db.Integer, default=0)
    date          = db.Column(db.DateTime, default=datetime.utcnow)
    weak_areas    = db.Column(db.String(200), default='')


class Recommendation(db.Model):
    """Personalized learning recommendations generated by the ML engine."""
    __tablename__ = 'recommendations'

    id             = db.Column(db.Integer, primary_key=True)
    user_id        = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    recommendation = db.Column(db.Text, nullable=False)
    reason         = db.Column(db.Text)
    suggested_time = db.Column(db.String(50))
    drift_status   = db.Column(db.String(30))   # Stable | Mild Drift | High Drift
    next_action    = db.Column(db.Text)
    date           = db.Column(db.DateTime, default=datetime.utcnow)


class DailyCheckin(db.Model):
    """Student's daily self-reported study session log."""
    __tablename__ = 'daily_checkins'

    id                = db.Column(db.Integer, primary_key=True)
    user_id           = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    date              = db.Column(db.Date, default=date.today)
    study_duration    = db.Column(db.Float, default=0.0)   # hours
    topics_studied    = db.Column(db.String(300), default='')
    quiz_score        = db.Column(db.Float, default=0.0)
    questions_attempted = db.Column(db.Integer, default=0)
    response_time     = db.Column(db.Float, default=45.0)
    difficulty_level  = db.Column(db.String(20), default='medium')
    engagement_level  = db.Column(db.Integer, default=3)
    note              = db.Column(db.Text, default='')
    created_at        = db.Column(db.DateTime, default=datetime.utcnow)


# ─────────────────────────────────────────────
# Seed Demo Data
# ─────────────────────────────────────────────

def seed_demo_data(app):
    """
    Seed the demo student 'Arthi' with realistic historical data
    that demonstrates cognitive drift detection in action.
    """
    with app.app_context():
        # Skip seeding if already done
        if User.query.filter_by(email='arthi@demo.com').first():
            return

        # ── Create demo user ──────────────────────────────────────
        arthi = User(
            name='Arthi',
            email='arthi@demo.com',
            xp=1240,
            streak=5,
            subject='Machine Learning',
            badges=json.dumps(['🏆 First Quiz', '🔥 5-Day Streak', '📚 3 Topics Completed'])
        )
        arthi.set_password('demo123')
        db.session.add(arthi)
        db.session.flush()   # get arthi.id before committing

        # ── Topics pool ───────────────────────────────────────────
        topics = ['Python', 'Machine Learning', 'Data Structures', 'Statistics', 'Mathematics']

        # ── Generate 30 days of learning activity ─────────────────
        # Days 1-14: Good performance (Stable)
        # Days 15-30: Slight dip (Mild Drift) – shows the system working
        today = date.today()

        for i in range(30, 0, -1):
            activity_date = today - timedelta(days=i)
            # Skip 4 random days to simulate real-world gaps
            if i in [27, 22, 18, 12, 8]:
                continue

            if i > 15:
                # Stable phase
                score      = random.uniform(78, 92)
                hours      = random.uniform(2.5, 4.5)
                resp_time  = random.uniform(20, 40)
                engagement = random.randint(4, 5)
            else:
                # Mild Drift phase
                score      = random.uniform(58, 74)
                hours      = random.uniform(1.2, 2.5)
                resp_time  = random.uniform(48, 68)
                engagement = random.randint(2, 4)

            activity = LearningActivity(
                user_id=arthi.id,
                date=activity_date,
                study_hours=round(hours, 1),
                quiz_score=round(score, 1),
                response_time=round(resp_time, 1),
                engagement_level=engagement,
                topics_studied=random.choice(topics)
            )
            db.session.add(activity)

        # ── Generate quiz history ─────────────────────────────────
        quiz_data = [
            ('Python',          'easy',   88, 5, 4, today - timedelta(days=28)),
            ('Machine Learning','easy',   80, 5, 4, today - timedelta(days=25)),
            ('Data Structures', 'medium', 75, 5, 3, today - timedelta(days=21)),
            ('Statistics',      'easy',   82, 5, 4, today - timedelta(days=18)),
            ('Mathematics',     'medium', 70, 5, 3, today - timedelta(days=15)),
            ('Python',          'medium', 72, 5, 3, today - timedelta(days=12)),
            ('Machine Learning','medium', 65, 5, 3, today - timedelta(days=9)),
            ('Data Structures', 'medium', 60, 5, 3, today - timedelta(days=6)),
            ('Statistics',      'hard',   58, 5, 2, today - timedelta(days=3)),
            ('Machine Learning','hard',   62, 5, 3, today - timedelta(days=1)),
        ]

        for topic, diff, score, total, correct, q_date in quiz_data:
            quiz = QuizResult(
                user_id=arthi.id,
                topic=topic,
                score=score,
                difficulty=diff,
                num_questions=total,
                correct=correct,
                date=datetime.combine(q_date, datetime.min.time()),
                weak_areas='Classification' if topic == 'Machine Learning' else ''
            )
            db.session.add(quiz)

        # ── Generate recommendation history ───────────────────────
        rec_history = [
            ('Continue with Supervised Learning',
             'Your recent quiz scores are strong. You are ready to move forward.',
             '45–60 minutes', 'Stable',
             'Take a practice quiz on Supervised Learning.',
             today - timedelta(days=20)),
            ('Revise Machine Learning Basics',
             'Your last two quizzes show a slight decline in performance.',
             '20–30 minutes', 'Mild Drift',
             'Take a 5-question beginner quiz to rebuild confidence.',
             today - timedelta(days=5)),
            ('Review Classification Concepts',
             'Your response time has increased and quiz scores dropped in Classification.',
             '25 minutes', 'Mild Drift',
             'Watch a concept explanation video, then attempt 5 practice questions.',
             today - timedelta(days=1)),
        ]

        for rec_text, reason, sug_time, drift, next_action, rec_date in rec_history:
            rec = Recommendation(
                user_id=arthi.id,
                recommendation=rec_text,
                reason=reason,
                suggested_time=sug_time,
                drift_status=drift,
                next_action=next_action,
                date=datetime.combine(rec_date, datetime.min.time())
            )
            db.session.add(rec)

        db.session.commit()
        print("[LearnFlow AI] Demo data seeded successfully for Arthi (arthi@demo.com / demo123).")
